// GENERATED by scripts/migrate-team.mjs — do not edit by hand.
// Source: https://bhutaneseincanberra.org.au/ourteam/ (migrated 2026-07-24)

export type Exec = {
  slug: string;
  name: string;
  role: string;
  bio: string;
  image: string | null;
};

export type FormerPresident = {
  slug: string;
  name: string;
  tenure: string;
  founder: boolean;
  image: string | null;
};

export const EXECUTIVE: Exec[] = [
  {
    "slug": "dorji-tashi",
    "name": "Dorji Tashi",
    "role": "President",
    "bio": "Mr. Dorji Tashi is the President of ABAC, bringing diverse academic and professional experience from Bhutan, India, Japan, and Australia. He holds a Bachelor's degree in Nursing Studies and a Master's in Business from Australia. He is Social worker by heart, entrepreneur by calling.",
    "image": "/img/team/dorji-tashi.jpeg"
  },
  {
    "slug": "jigme-jamtsho",
    "name": "Jigme Jamtsho",
    "role": "Vice President & Public Relations Officer",
    "bio": "Mr. Jigme Jamtsho serves as the Vice President and Public Relations Officer of ABAC, bringing strong leadership and a deep commitment to serving the Bhutanese community in Canberra.",
    "image": "/img/team/jigme-jamtsho.jpeg"
  },
  {
    "slug": "kuenzang-dema",
    "name": "Kuenzang Dema",
    "role": "General Secretary",
    "bio": "Mrs. Kuenzang Dema is the General Secretary of ABAC with a strong passion for community service and social impact. She completed a Master of Social Work in Australia. Currently working as a Child Protection Case Manager and Dzongkha Interpreter.",
    "image": "/img/team/kuenzang-dema.jpeg"
  },
  {
    "slug": "tshering-phuntsho",
    "name": "Tshering Phuntsho",
    "role": "Treasurer",
    "bio": "Mr. Tshering Phuntsho serves as the Treasurer of ABAC, bringing extensive experience in finance and public service. Master of Professional Accounting from the University of Canberra.",
    "image": "/img/team/tshering-phuntsho.jpeg"
  },
  {
    "slug": "pema-yogini-yuphel",
    "name": "Pema Yogini Yuphel",
    "role": "Community Engagement Officer",
    "bio": "Mrs. Pema Yogini Yuphel is ABAC's Community Engagement Officer, a renowned Bhutanese actress, youth advocate, and social media influencer.",
    "image": "/img/team/pema-yogini-yuphel.jpeg"
  },
  {
    "slug": "tandin-sonam",
    "name": "Tandin Sonam",
    "role": "Sports Coordinator",
    "bio": "Mr. Tandin Sonam is the Games and Sports Coordinator of ABAC and is passionate about promoting sports, fitness, and community wellbeing. He holds a Bachelor of Arts in English Studies.",
    "image": "/img/team/tandin-sonam.jpeg"
  },
  {
    "slug": "sangay-tshomo",
    "name": "Sangay Tshomo",
    "role": "Cultural Coordinator",
    "bio": "Mrs. Sangay Tshomo serves as ABAC's Cultural Coordinator and is dedicated to preserving and promoting Bhutanese culture through traditional songs and dances. She has represented Bhutanese cultural heritage internationally and actively collaborates with artists.",
    "image": "/img/team/sangay-tshomo.jpeg"
  },
  {
    "slug": "leki-dorji",
    "name": "Leki Dorji",
    "role": "Youth Coordinator",
    "bio": "Mr.Leki Dorji is the Youth Representative of ABAC. He has completed master in Data Science and Artificial Intelligence.",
    "image": "/img/team/leki-dorji.jpeg"
  },
  {
    "slug": "phuntsho-kinrab-dema",
    "name": "Phuntsho Kinrab Dema",
    "role": "Community Engagement Officer",
    "bio": "Mrs. Phuntsho Kinrab Dema is a well-recognised Bhutanese actress and influential social media content creator. She holds a Bachelor’s degree from Sherubtse College and has recently commenced in a Master of Communication at the University of Canberra.",
    "image": "/img/team/phuntsho-kinrab-dema.jpeg"
  }
];

export const FORMER_PRESIDENTS: FormerPresident[] = [
  {
    "name": "Ugyen Penjor",
    "tenure": "2025-2026",
    "founder": false,
    "slug": "ugyen-penjor",
    "image": null
  },
  {
    "name": "Jigme Jamtsho",
    "tenure": "2025 – 2026",
    "founder": false,
    "slug": "jigme-jamtsho",
    "image": "/img/team/prez-jigme-jamtsho-2025-2026.jpeg"
  },
  {
    "name": "Alu Passa",
    "tenure": "2023 – 2024, 2014 – 2015",
    "founder": false,
    "slug": "alu-passa",
    "image": "/img/team/prez-alu-passa-2023-2024-2014-2015.jpg"
  },
  {
    "name": "Dorji Tshering",
    "tenure": "2022 – 2023",
    "founder": false,
    "slug": "dorji-tshering",
    "image": "/img/team/prez-dorji-tshering-2022-2023.jpg"
  },
  {
    "name": "Tshering Penjor",
    "tenure": "2021 – 2022",
    "founder": false,
    "slug": "tshering-penjor",
    "image": "/img/team/prez-tshering-penjor-2021-2022.jpg"
  },
  {
    "name": "Karma Drupchu",
    "tenure": "2020 – 2021",
    "founder": false,
    "slug": "karma-drupchu",
    "image": "/img/team/prez-karma-drupchu-2020-2021.jpg"
  },
  {
    "name": "Dorji Tshering",
    "tenure": "2019 – 2020",
    "founder": false,
    "slug": "dorji-tshering",
    "image": "/img/team/prez-dorji-tshering-2019-2020.jpg"
  },
  {
    "name": "Chencho Tshering",
    "tenure": "2018 – 2019",
    "founder": false,
    "slug": "chencho-tshering",
    "image": "/img/team/prez-chencho-tshering-2018-2019.jpg"
  },
  {
    "name": "Tashi Pelden",
    "tenure": "2017 – 2018",
    "founder": false,
    "slug": "tashi-pelden",
    "image": null
  },
  {
    "name": "Tandin Dorji",
    "tenure": "2017 – 2018",
    "founder": false,
    "slug": "tandin-dorji",
    "image": null
  },
  {
    "name": "Namgyel Dorji",
    "tenure": "2015 – 2016",
    "founder": false,
    "slug": "namgyel-dorji",
    "image": null
  },
  {
    "name": "Sonam Choden",
    "tenure": "2013 – 2014",
    "founder": false,
    "slug": "sonam-choden",
    "image": "/img/team/prez-sonam-choden-2013-2014.jpg"
  },
  {
    "name": "Ugyen Namgay",
    "tenure": "2012 – 2013",
    "founder": false,
    "slug": "ugyen-namgay",
    "image": "/img/team/prez-ugyen-namgay-2012-2013.jpg"
  },
  {
    "name": "Phub Dorji",
    "tenure": "2011 – 2012",
    "founder": false,
    "slug": "phub-dorji",
    "image": "/img/team/prez-phub-dorji-2011-2012.jpg"
  },
  {
    "name": "Sonam Tobgye",
    "tenure": "2010 – 2011",
    "founder": true,
    "slug": "sonam-tobgye",
    "image": null
  }
];
